Create ADR for conflicting contributions
open-constructs/aws-cdk-library pull request #20
Opened 2024-04-28 20:46 UTC by dbartholomae

See #13 for previous related discussions

2024-04-28 22:47 UTC, mbonig commented on decisions/ADR-04-conflicting-contributions.md
> +On the other hand, one of the goals of this library is to provide thoroughly testede solutions to make it easier for enterprise users to consume just one approved library.
```suggestion
On the other hand, one of the goals of this library is to provide thoroughly tested solutions to make it easier for enterprise users to consume just one approved library.
```

2024-04-28 22:47 UTC, mbonig commented on decisions/ADR-04-conflicting-contributions.md
> +## Combine learnings from multiple solutions
Should this be a '###'?

2024-04-29 03:53 UTC, go-to-k requested changes

2024-04-29 03:53 UTC, go-to-k commented on decisions/ADR-04-conflicting-contributions.md
> +### Decide for a competing solutino
```suggestion
### Decide for a competing solution
```

2024-05-01 20:49 UTC, dbartholomae commented on decisions/ADR-04-conflicting-contributions.md
> +## Combine learnings from multiple solutions
Yes, thanks!

```suggestion
### Combine learnings from multiple solutions
```

2024-05-02 05:22 UTC, go-to-k approved these changes

2024-05-02 21:39 UTC, merged