chore: add prettier config
open-constructs/aws-cdk-library pull request #31
Opened 2024-05-26 15:23 UTC by WinterYukky

Add Prettier as a code styling tool.
By introducing prettier, it is possible to make the code style consistent. Also, if there are contributors using prettier as an IDE, their code will be formatted based on prettier's default settings, but they may conflict with Eslint. It would be a good idea to prepare settings on the project side.

Fortunately, projen supports prettier, so you only need to set up a few lines of `projenrc.ts`.

2024-05-26 16:37 UTC, hoegertn commented on src/aws-cur/cost-report.ts
> +  public static readonly HOURLY: ReportGranularity = new ReportGranularity(
I am not a fan of this change

2024-05-26 16:38 UTC, hoegertn commented on src/aws-ec2/instance-connect-endpoint.ts
> +export interface IInstanceConnectEndpoint
Please not

2024-05-26 16:39 UTC, hoegertn commented on src/aws-ec2/instance-connect-endpoint.ts
> +      securityGroupIds: this.securityGroups.map((sg) => sg.securityGroupId),
debatable

2024-05-26 16:39 UTC, hoegertn commented on test/aws-ec2/instance-connect-endpoint.test.ts
> -    Template.fromStack(stack).hasResourceProperties('AWS::EC2::InstanceConnectEndpoint', {
In general yes, but sometimes I think it is better readable to collapse some KV-pairs

2024-05-26 16:40 UTC, hoegertn requested changes
I love the idea
I am not a fan of the format

2024-05-27 15:17 UTC, mrgrain commented
This is certainly a good idea. 👍

Personally I don't have a strong opinion about specific formatting options as long as it's consistent and enforced.

2024-05-27 15:43 UTC, WinterYukky commented
As long as it's consistent like @mrgrain , I'm not particular about anything else. I tried increasing the range allowed by Prettier so that it would be @hoegertn 's favorite format.

2024-05-27 16:03 UTC, mrgrain commented on .projenrc.ts
> +      printWidth: 100,
The previous ESLint rule used 150. I think that's maybe a bit excessive, but 120 might be a good compromise.

```suggestion
      printWidth: 120,
```

2024-05-27 16:21 UTC, WinterYukky commented
Self-mutation is also a good match. If a contributor forgets to format it, there's no need to point it out.

2024-05-27 17:56 UTC, hoegertn commented
Still not a big fan of the excessive newlines. Can't we use prettier but with the same settings as before?
These were a good fit and are also basically what every CDK / projen projects uses.

2024-05-29 17:33 UTC, dbartholomae commented
Prettier, [by design](https://prettier.io/docs/en/option-philosophy), isn't really that configurable, so I'm not sure if we can match specific ideas. To be honest, I would personally prefer to use prettier with as little changes as possible, as this enforces the notion that codestyle usually isn't the most important thing to discuss - but I'm also in the camp that doesn't really care how exactly we format the code.

My suggestion would be maybe @hoegertn you can check [which of the options](https://prettier.io/docs/en/options) you care about and we can then update the config accordingly. I don't think we will be able to pixel-perfect match the old style, but maybe we can at least get close on what matters.

2024-05-29 18:33 UTC, hoegertn commented
I think I am fine with the selected options but I really hate the excessive newlines.

But if we decide we want to use prettier I will live with it.

2024-07-03 22:28 UTC, hoegertn approved these changes
Not a fan but ok with it

2024-07-03 22:34 UTC, merged